---
###############################################################
# HADOLINT configuration (a Dockerfile linter)
###############################################################
# source           : https://github.com/hadolint/hadolint
# online validator : https://hadolint.github.io/hadolint/
# docker image     : https://hub.docker.com/r/hadolint/hadolint
###############################################################
trustedRegistries:
  - docker.io
ignored:
  - DL3008
#   - DL3009
#   - DL3015
########################################################################################################################
# Rules currently not applied:  ---> @TODO to be corrected
#   DL3008 Pin versions in apt install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
#   DL3009 Delete the apt-get lists after installing something
#   DL3015 Avoid additional packages by specifying `--no-install-recommends`
########################################################################################################################
