---
###################################################
# Config for yamllint
# https://yamllint.readthedocs.io
# https://github.com/adrienverge/yamllint
###################################################
extends: default
rules:
  comments-indentation: disable
  line-length:
    max: 120
    level: warning
  empty-lines:
    max: 2
    level: warning
