---
#### LINTER ######################################################################################################
# markdownlint              ---> Markdown files linter
# Yamllint                  ---> Yaml files linter
# Dockerfileslint           ---> Dockerfiles linter
# JsonLint                  ---> JSON files linter
##################################################################################################################

###############################################################
# markdownlint     https://github.com/DavidAnson/markdownlint
#                  https://github.com/igorshubovych/markdownlint-cli
# --> a CI job that will lint all markdown files
###############################################################
markdown_linter:
  stage: lint
  image:
    name: ghcr.io/igorshubovych/markdownlint-cli:v0.41.0
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  before_script:
    - markdownlint --version
    - cat .gitlab/ci/config/markdownlint.yml
    - cat .gitlab/ci/config/markdownlintignore.txt
  script:
    - markdownlint '**/*.md' --config .gitlab/ci/config/markdownlint.yml -p .gitlab/ci/config/markdownlintignore.txt
    - markdownlint --version

###############################################################
# Yamllint      https://yamllint.readthedocs.io
#               https://github.com/adrienverge/yamllint
#               https://github.com/sdesbure/docker_yamllint
#               https://manpages.debian.org/buster/yamllint/yamllint.1.en.html
# --> a CI job that will lint all YAML files (docker-compose.yml, .gitlab/ci/*.yml)
###############################################################
yaml_linter:
  stage: lint
  image: sdesbure/yamllint:latest
  script:
    - find . -name '*.yaml' -type f
    - find . -name '*.yml'  -type f
    - find . -name '*.yaml' -type f -not -path "./.gitlab/website_hugo/themes/*"
      | xargs -I % yamllint -c .gitlab/ci/config/yamllint.yaml %
    - find . -name '*.yml'  -type f -not -path "./.gitlab/website_hugo/themes/*"
      | xargs -I % yamllint -c .gitlab/ci/config/yamllint.yaml %


###############################################################
# Hadolint     https://github.com/hadolint/hadolint
#              https://hadolint.github.io/hadolint/
#              https://hub.docker.com/r/hadolint/hadolint
# --> a CI job that will lint all Dockerfile files
###############################################################
DockerFile_linter:
  stage: lint
  image: hadolint/hadolint:latest-alpine
  script:
    - find . -type f -name Dockerfile* | xargs -I % ls -l %
    - cat .gitlab/ci/config/hadolint.yml
    - find . -type f -name Dockerfile* | xargs -I % hadolint --config .gitlab/ci/config/hadolint.yml %
    ##############################################################################################
    # Rules currently not applied:  ---> see: .gitlab/ci/config/hadolint.yml (@FIXME)
    #       DL3003 Use WORKDIR to switch to a directory
    #       DL3008 Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
    #       DL3009 Delete the apt-get lists after installing something
    #       DL3025 Use arguments JSON notation for CMD and ENTRYPOINT arguments
    ##############################################################################################
